<?php

use app\constants\DisbursementOrder;

return [
    DisbursementOrder::BILL_TEMPLATE_ICICI     => [
        'down_filename'        => 'order_icicicorporate_bank_card_no_' . date('YmdHis'),
        'down_filepath'        => '/public/download/bill/icici/',
        'down_dto_class'       => \app\service\bankbill\down\DtoBillOfICICI::class,
        'down_sheetIndex'      => 0,
        'down_suffix'          => 'xlsx',
        'upload_example_file'  => '/templates/ICICI导入订单格式.xlsx',
        'upload_directory'     => 'icici',
        'upload_service_class' => \app\service\BankDisbursementBillIciciService::class,
    ],
    DisbursementOrder::BILL_TEMPLATE_ICICI2    => [
        'down_filename'        => 'order_icicicorporate_bank_card_no_' . date('YmdHis'),
        'down_filepath'        => '/public/download/bill/icici2/',
        'down_dto_class'       => \app\service\bankbill\down\DtoBillOfICICI2::class,
        'down_sheetIndex'      => 0,
        'down_suffix'          => 'xlsx',
        'upload_example_file'  => '/templates/ICICI2导入订单格式.xls',
        'upload_directory'     => 'icici',
        'upload_service_class' => \app\service\BankDisbursementBillIcici2Service::class,
    ],
    DisbursementOrder::BILL_TEMPLATE_BANDHAN   => [
        'down_filename'        => 'BULK_' . substr(date('dmY'), 0, 2) . substr(date('dmY'), 4, 2) . substr(date('dmY'), -2) . '_' . date('His'),
        'down_filepath'        => '/public/download/bill/bandhan/',
        'down_dto_class'       => \app\service\bankbill\down\DtoBillOfBandHan::class,
        'down_sheetIndex'      => 1,
        'down_suffix'          => 'xlsx',
        'upload_example_file'  => '/templates/BANDHAN导入订单格式.csv',
        'upload_directory'     => 'bandhan',
        'upload_service_class' => \app\service\BankDisbursementBillBandhanService::class,
    ],
    DisbursementOrder::BILL_TEMPLATE_YES_MSME  => [
        'down_filename'        => 'IMPS SDSC',
        'down_filepath'        => '/public/download/bill/yesmsme/',
        'down_dto_class'       => \app\service\bankbill\down\DtoBillOfYesMsMe::class,
        'down_sheetIndex'      => 0,
        'down_suffix'          => 'xlsx',
        'upload_example_file'  => '/templates/YES导入账单格式.csv',
        'upload_directory'     => 'yesmsme',
        'upload_service_class' => \app\service\BankDisbursementBillYesmsmeService::class,
    ],
    DisbursementOrder::BILL_TEMPLATE_AXIS      => [
        'down_filename'        => 'order_axiscorporate_bank_card_no_' . date('YmdHis'),
        'down_filepath'        => '/public/download/bill/axis/',
        'down_dto_class'       => \app\service\bankbill\down\DtoBillOfAxis::class,
        'down_sheetIndex'      => 0,
        'down_suffix'          => 'xlsx',
        'upload_example_file'  => '/templates/AXIS导入订单格式.xlsx',
        'upload_directory'     => 'axis',
        'upload_service_class' => \app\service\BankDisbursementBillAxisService::class,
    ],
    DisbursementOrder::BILL_TEMPLATE_AXIS_NEFT => [
        'down_filename'        => 'order_axis_neftcorporate_bank_card_no_' . date('YmdHis'),
        'down_filepath'        => '/public/download/bill/axisneft/',
        'down_dto_class'       => \app\service\bankbill\down\DtoBillOfAxisNeft::class,
        'down_sheetIndex'      => 0,
        'down_suffix'          => 'xlsx',
        'upload_example_file'  => '/templates/AXISNEFT导入订单格式.xlsx',
        'upload_directory'     => 'axisneft',
        'upload_service_class' => \app\service\BankDisbursementBillAxisNeftService::class,
    ],
    DisbursementOrder::BILL_TEMPLATE_AXIS_NEO  => [
        'down_filename'        => 'order_axis_neftcorporate_ank_card_no_' . date('YmdHis'),
        'down_filepath'        => '/public/download/bill/axisneo/',
        'down_dto_class'       => \app\service\bankbill\down\DtoBillOfAxisNeo::class,
        'down_sheetIndex'      => 0,
        'down_suffix'          => 'xlsx',
        'upload_example_file'  => '/templates/AXISNEO导入订单格式.xlsx',
        'upload_directory'     => 'axisneo',
        'upload_service_class' => \app\service\BankDisbursementBillAxisNeoService::class,
    ],
    DisbursementOrder::BILL_TEMPLATE_IDFC      => [
        'down_filename'        => 'order_idfccorporate_bank_card_no_' . date('YmdHis'),
        'down_filepath'        => '/public/download/bill/idfc/',
        'down_dto_class'       => \app\service\bankbill\down\DtoBillOfIdfc::class,
        'down_sheetIndex'      => 0,
        'down_suffix'          => 'xlsx',
        'upload_example_file'  => '/templates/IDFC导入账单格式.xlsx',
        'upload_directory'     => 'idfc',
        'upload_service_class' => \app\service\BankDisbursementBillIdfcService::class,
    ],
    DisbursementOrder::BILL_TEMPLATE_IOB_SAME  => [
        'down_filename'        => 'order_iobsamebank_bank_card_no_' . date('YmdHis'),
        'down_filepath'        => '/public/download/bill/iobsamebank/',
        'down_dto_class'       => \app\service\bankbill\down\DtoBillOfIobSame::class,
        'down_sheetIndex'      => 0,
        'down_suffix'          => 'xlsx',
        'upload_example_file'  => '/templates/IOBSameBank导入订单格式.csv',
        'upload_directory'     => 'iobsamebank',
        'upload_service_class' => \app\service\BankDisbursementBillIobSameService::class,
    ],
    DisbursementOrder::BILL_TEMPLATE_IOB_OTHER => [
        'down_filename'        => 'order_iobotherbank_bank_card_no_' . date('YmdHis'),
        'down_filepath'        => '/public/download/bill/iobotherbank/',
        'down_dto_class'       => \app\service\bankbill\down\DtoBillOfIobOther::class,
        'down_sheetIndex'      => 0,
        'down_suffix'          => 'xlsx',
        'upload_example_file'  => '/templates/IOBOtherBank导入订单格式.csv',
        'upload_directory'     => 'iobotherbank',
        'upload_service_class' => \app\service\BankDisbursementBillIobOtherService::class,
    ],
];